In [2]:
import pandas as pd

In [4]:
df_ga_hits = pd.read_csv('ga_hits.csv')

In [10]:
df_ga_hits.head(20)

,session_id,hit_date,hit_time,hit_number,hit_type,hit_referer,hit_page_path,event_category,event_action,event_label,event_value
0,5639623078712724064.1640254056.1640254056,2021-12-23,597864.0,30,event,NaN,sberauto.com/cars?utm_source_initial=google&ut...,quiz,quiz_show,NaN,NaN
1,7750352294969115059.1640271109.1640271109,2021-12-23,597331.0,41,event,NaN,sberauto.com/cars/fiat?city=1&city=18&rental_c...,quiz,quiz_show,NaN,NaN
2,885342191847998240.1640235807.1640235807,2021-12-23,796252.0,49,event,NaN,sberauto.com/cars/all/volkswagen/polo/e994838f...,quiz,quiz_show,NaN,NaN
3,142526202120934167.1640211014.1640211014,2021-12-23,934292.0,46,event,NaN,sberauto.com/cars?utm_source_initial=yandex&ut...,quiz,quiz_show,NaN,NaN
4,3450086108837475701.1640265078.1640265078,2021-12-23,768741.0,79,event,NaN,sberauto.com/cars/all/mercedes-benz/cla-klasse...,quiz,quiz_show,NaN,NaN
5,6466333295973247896.1640246168.1640246168,2021-12-23,704194.0,41,event,NaN,sberauto.com/cars?utm_source_initial=youtube&u...,quiz,quiz_show,NaN,NaN
6,281215510786615563.1640245516.1640245516,2021-12-23,911854.0,102,event,NaN,sberauto.com/cars/toyota?isnew=false&rental_ca...,quiz,quiz_show,NaN,NaN
7,4024492994895054107.1640269084.1640269084,2021-12-23,1071804.0,85,event,NaN,sberauto.com/cars/all/mercedes-benz/glc/f8f330...,quiz,quiz_show,NaN,NaN
8,555009234841130092.1640256620.1640256620,2021-12-23,1013899.0,101,event,VloVXNWduHeTjUoDkjkO,sberauto.com/cars/all/kia/sorento/c38179cb?utm...,quiz,quiz_show,NaN,NaN
9,2692901778487480807.1640206845.1640206845,2021-12-23,0.0,1,event,NaN,sberauto.com/cars/all/nissan/x-trail/0744675f?...,card_web,view_card,NaN,NaN
10,1945627655676404094.1640276355.1640276355,2021-12-23,197.0,4,event,NaN,sberauto.com/cars/all/porsche/911/f149c91b?ren...,card_web,view_card,NaN,NaN
11,4555345648396008371.1640233907.1640233907,2021-12-23,107.0,4,event,trXmoxcphNjuYcShOXwL,sberauto.com/cars/all/nissan/qashqai/bfc21661?...,card_web,view_card,NaN,NaN
12,5636135307570360848.1640280592.1640280592,2021-12-23,12.0,3,event,NaN,sberauto.com/cars/all/renault/duster/145d53f1?...,card_web,view_card,NaN,NaN
13,6993187768713388524.1640276467.1640276467,2021-12-23,1186.0,4,event,NaN,sberauto.com/cars/all/porsche/911/f149c91b?ren...,card_web,view_card,NaN,NaN
14,9063469723165129646.1640233902.1640233902,2021-12-23,68.0,3,event,uMnMdxLOIznakHyXLoMC,sberauto.com/cars/all/skoda/rapid/bf24b977?ren...,card_web,view_card,NaN,NaN
15,9221311837172398962.1640233841.1640233841,2021-12-23,506.0,3,event,trXmoxcphNjuYcShOXwL,sberauto.com/cars/all/skoda/rapid/bf24b977?ren...,card_web,view_card,NaN,NaN
16,8279923128365523547.1640276571.1640276571,2021-12-23,1024.0,3,event,uMnMdxLOIznakHyXLoMC,sberauto.com/cars/all/porsche/911/f149c91b?ren...,card_web,view_card,NaN,NaN
17,9126144797936188300.1640233869.1640233869,2021-12-23,488.0,3,event,NaN,sberauto.com/cars/all/renault/logan/8c3c73f2?r...,card_web,view_card,NaN,NaN
18,1333511261702627793.1640276433.1640276433,2021-12-23,5618.0,6,event,NaN,sberauto.com/cars/all/porsche/911/f149c91b?ren...,card_web,view_card,NaN,NaN
19,699466478407410560.1640289549.1640289549,2021-12-23,20.0,6,event,NaN,sberauto.com/cars/all/peugeot/traveller/4c1dd8...,card_web,view_card,NaN,NaN

In [8]:
df_ga_hits_copy = df_ga_hits.copy()

In [25]:
drop_list = ['hit_type','hit_time','hit_date','event_category','event_label','event_value']

In [ ]:
df_ga_hits_copy = df_ga_hits_copy.drop(columns = drop_list)

In [28]:
df_ga_hits_copy.head(5)

,session_id,hit_number,hit_referer,hit_page_path,event_action
0,5639623078712724064.1640254056.1640254056,30,NaN,sberauto.com/cars?utm_source_initial=google&ut...,quiz_show
1,7750352294969115059.1640271109.1640271109,41,NaN,sberauto.com/cars/fiat?city=1&city=18&rental_c...,quiz_show
2,885342191847998240.1640235807.1640235807,49,NaN,sberauto.com/cars/all/volkswagen/polo/e994838f...,quiz_show
3,142526202120934167.1640211014.1640211014,46,NaN,sberauto.com/cars?utm_source_initial=yandex&ut...,quiz_show
4,3450086108837475701.1640265078.1640265078,79,NaN,sberauto.com/cars/all/mercedes-benz/cla-klasse...,quiz_show

In [23]:
df_ga_hits_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15726470 entries, 0 to 15726469
Data columns (total 5 columns):
 #   Column         Dtype
---  ------         -----
 0   session_id     object
 1   hit_number     int64
 2   hit_referer    object
 3   hit_page_path  object
 4   event_action   object
dtypes: int64(1), object(4)
memory usage: 599.9+ MB

In [61]:
len(df_ga_hits_copy)

15726470

In [63]:
df_ga_hits_copy.hit_referer = df_ga_hits_copy.hit_referer.fillna('other')

In [64]:
df_ga_hits_copy.isna().sum()

session_id       0
hit_number       0
hit_referer      0
hit_page_path    0
event_action     0
dtype: int64

In [29]:
df_ga_sessions = pd.read_csv('ga_sessions.csv')

C:\Users\admin\AppData\Local\Temp\ipykernel_9656\434350226.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ga_sessions = pd.read_csv('ga_sessions.csv')

In [30]:
df_ga_sessions.head(5)

,session_id,client_id,visit_date,visit_time,visit_number,utm_source,utm_medium,utm_campaign,utm_adcontent,utm_keyword,device_category,device_os,device_brand,device_model,device_screen_resolution,device_browser,geo_country,geo_city
0,9055434745589932991.1637753792.1637753792,2108382700.163776,2021-11-24,14:36:32,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,mobile,Android,Huawei,NaN,360x720,Chrome,Russia,Zlatoust
1,905544597018549464.1636867290.1636867290,210838531.163687,2021-11-14,08:21:30,1,MvfHsxITijuriZxsqZqt,cpm,FTjNLDyTrXaWYgZymFkV,xhoenQgDQsgfEPYNPwKO,IGUCNvHlhfHpROGclCit,mobile,Android,Samsung,NaN,385x854,Samsung Internet,Russia,Moscow
2,9055446045651783499.1640648526.1640648526,2108385331.164065,2021-12-28,02:42:06,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,mobile,Android,Huawei,NaN,360x720,Chrome,Russia,Krasnoyarsk
3,9055447046360770272.1622255328.1622255328,2108385564.162225,2021-05-29,05:00:00,1,kjsLglQLzykiRbcDiGcD,cpc,NaN,NOBKLgtuvqYWkXQHeYWM,NaN,mobile,NaN,Xiaomi,NaN,393x786,Chrome,Russia,Moscow
4,9055447046360770272.1622255345.1622255345,2108385564.162225,2021-05-29,05:00:00,2,kjsLglQLzykiRbcDiGcD,cpc,NaN,NaN,NaN,mobile,NaN,Xiaomi,NaN,393x786,Chrome,Russia,Moscow

In [36]:
drop_list_ga_s = ['device_screen_resolution', 'device_model','visit_time','visit_date','utm_adcontent']

In [34]:
df_ga_session_copy = df_ga_sessions.copy()

In [38]:
df_ga_session_copy = df_ga_session_copy.drop(columns = drop_list_ga_s)

In [39]:
df_ga_session_copy.head(5)

,session_id,client_id,visit_number,utm_source,utm_medium,utm_campaign,utm_keyword,device_category,device_os,device_brand,device_browser,geo_country,geo_city
0,9055434745589932991.1637753792.1637753792,2108382700.163776,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,puhZPIYqKXeFPaUviSjo,mobile,Android,Huawei,Chrome,Russia,Zlatoust
1,905544597018549464.1636867290.1636867290,210838531.163687,1,MvfHsxITijuriZxsqZqt,cpm,FTjNLDyTrXaWYgZymFkV,IGUCNvHlhfHpROGclCit,mobile,Android,Samsung,Samsung Internet,Russia,Moscow
2,9055446045651783499.1640648526.1640648526,2108385331.164065,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,puhZPIYqKXeFPaUviSjo,mobile,Android,Huawei,Chrome,Russia,Krasnoyarsk
3,9055447046360770272.1622255328.1622255328,2108385564.162225,1,kjsLglQLzykiRbcDiGcD,cpc,NaN,NaN,mobile,NaN,Xiaomi,Chrome,Russia,Moscow
4,9055447046360770272.1622255345.1622255345,2108385564.162225,2,kjsLglQLzykiRbcDiGcD,cpc,NaN,NaN,mobile,NaN,Xiaomi,Chrome,Russia,Moscow

In [59]:
df_ga_session_copy.isna().sum()

session_id         0
client_id          0
visit_number       0
utm_source         0
utm_medium         0
utm_campaign       0
utm_keyword        0
device_category    0
device_os          0
device_brand       0
device_browser     0
geo_country        0
geo_city           0
dtype: int64

In [42]:
len(df_ga_session_copy)

1860042

In [44]:
df_ga_session_copy.utm_keyword = df_ga_session_copy.utm_keyword.fillna('unknown')

In [48]:
df_ga_session_copy.device_os = df_ga_session_copy.device_os.fillna('unknown')

In [49]:
df_ga_session_copy.device_brand = df_ga_session_copy.device_brand.fillna('unknown')

In [51]:
df_ga_session_copy.utm_source.mode()

0    ZpYIoDJMcFzVoPFsHGJL
Name: utm_source, dtype: object

In [56]:
df_ga_session_copy.utm_source = df_ga_session_copy.utm_source.fillna('ZpYIoDJMcFzVoPFsHGJL')

In [58]:
df_ga_session_copy.utm_campaign = df_ga_session_copy.utm_campaign.fillna('unknown')

In [65]:
df_ga_session_copy.to_csv('ga_sessions_prep')

In [67]:
df_ga_hits_copy.to_csv('ga_hits_prep')

In [80]:
df_ga_hits.event_action.value_counts()

view_card                     3558985
view_new_card                 3551009
sub_landing                   1798117
go_to_car_card                 973666
sub_view_cars_click            791515
                               ...
click_on_android                    1
new_year_road_help_btn              1
titul_page_view                     1
show_pos_status_declined            1
survey_buy_after_sell_when          1
Name: event_action, Length: 230, dtype: int64